global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["10.14.10.4:9090"]

  - job_name: "squire-node"
    static_configs:
      - targets: ["10.14.10.4:9100"]
