global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["10.14.10.4:9090"]

  - job_name: "squire-node"
    static_configs:
      - targets: ["10.14.10.4:9100"]

  - job_name: "mikrotik"
    static_configs:
      - targets: ["10.14.10.4:9200"]

  - job_name: "mateometer"
    static_configs:
      - targets: ["mate.at.hs3.pl"]

  - job_name: "mikrotik-tmp"
    static_configs:
      - targets: ["10.14.10.48:9436"]
      
  - job_name: "octoprint"
    scrape_interval: 5s
    metrics_path: "/plugin/prometheus_exporter/metrics"
    static_configs:
      - targets: ["10.14.10.17:80"]
