---
- hosts: all
  become: yes
  vars:
    apps:
      - name: netdata
        git_url: ~
      - name: spotty-kiwi
        git_url: ~
      - name: at
        git_url: https://github.com/hs3city/at.git
      - name: whois
        git_url: https://github.com/hs3city/whois.git
  roles:
    - role: laptop_server
      tags:
        - landscape
    - role: geerlingguy.docker
      docker_users:
        - hsop
      docker_package_state: latest
      tags:
        - landscape
        
    - role: nginxinc.nginx
      tags:
        - landscape

    - role: admin_utilities
      tags: customization
        - landscape
    - role: sshd_banner
      tags: customization

    - role: apps
      tags:
        - apps

    - role: backup
      tags:
        - maintenance

