---
- name: create "volumes" directory
  file: path=/var/opt/volumes state=directory

- name: create "src" directory
  file: path=/opt/src state=directory

- assert:
    that:
      - "'src' not in apps"
    msg: "'src' is reserved name"

- name: copy aplications' compose files
  copy:
    dest: /opt
    src: "{{ item }}"
  with_items: "{{ apps }}"

- name: run applications
  docker_service:
    project_src: /opt/{{ item }}
    pull: true
  with_items: "{{ apps }}"
