---
- name: create required directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ apps_compose_path }}"
    - "{{ apps_src_path }}"
    - "{{ apps_volumes_path }}"

- name: copy aplications' compose files
  copy:
    dest: "{{ apps_compose_path }}"
    src: "{{ item }}"
  with_items: "{{ apps | map(attribute='name') | list }}"

- name: run applications
  docker_service:
    project_src: "{{ apps_compose_path }}/{{ item }}"
    pull: true
  with_items: "{{ apps | map(attribute='name') | list }}"
