---
- name: install git - in order to clone Dotfiles repository
  package: name=git state=latest
  become: yes

- name: create required directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ apps_compose_path }}"
    - "{{ apps_src_path }}"
    - "{{ apps_volumes_path }}"

- name: copy aplications' sources for local build
  git:
    repo: "{{ item.git_url }}"
    dest: "{{ apps_src_path }}{{ item.name }}"
    version: master
    force: yes
  when: item.git_url
  with_items: "{{ apps }}"

- name: copy aplications' compose files
  template:
    dest: "{{ apps_compose_path }}{{ item }}/docker-compose.yml"
    src: "{{ item }}/docker-compose.j2"
    validate: docker-compose -f %s config
  with_items: "{{ apps | map(attribute='name') | list }}"

- name: run applications
  docker_service:
    project_src: "{{ apps_compose_path }}{{ item }}"
    pull: true
    build: true
  with_items: "{{ apps | map(attribute='name') | list }}"
