---
- name: create application data directory
  file:
    state: directory
    path: /var/eph/
  become: yes

- name: copy application configs
  copy:
    src: configs/
    dest: /etc/svc/
  become: yes
