---
- hosts: all
  vars:
    apps: ["netdata"]
  become: yes
  roles:
    # landscape
    - laptop_server
    - role: geerlingguy.docker
      docker_users:
        - hsop
      docker_package_state: latest

    # customization
    - admin_utilities
    - sshd_banner

    # apps
    - apps
