---
- hosts: all
  become: yes
  vars:
    apps:
      - name: netdata
        git_url: ~
      - name: at
        git_url: https://github.com/hs3city/at.git
      - name: whois
        git_url: https://github.com/hs3city/whois.git
  roles:

    # landscape
    - laptop_server
    - role: geerlingguy.docker
      docker_users:
        - hsop
      docker_package_state: latest

    # customization
    - admin_utilities
    - sshd_banner

    # apps
    - apps
    - backup
